// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuZzzlszW9EAIZlbIm_RD2DW16dfBvb0g',
    appId: '1:245625075246:web:a5b96d2e7e35e21b3011bf',
    messagingSenderId: '245625075246',
    projectId: 'acm-hackathon-a7eeb',
    authDomain: 'acm-hackathon-a7eeb.firebaseapp.com',
    storageBucket: 'acm-hackathon-a7eeb.firebasestorage.app',
    measurementId: 'G-Y27CZSP6JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSkfG7iOsBa2DYma5korjyWpWQ4HpOlNg',
    appId: '1:245625075246:android:30a5fcb79f6da3353011bf',
    messagingSenderId: '245625075246',
    projectId: 'acm-hackathon-a7eeb',
    storageBucket: 'acm-hackathon-a7eeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjfQbw-ZxA2waFf0qDdaFtX4XAMxfhwfk',
    appId: '1:245625075246:ios:75abe911eb2a6b513011bf',
    messagingSenderId: '245625075246',
    projectId: 'acm-hackathon-a7eeb',
    storageBucket: 'acm-hackathon-a7eeb.firebasestorage.app',
    iosBundleId: 'com.example.acmhackthon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjfQbw-ZxA2waFf0qDdaFtX4XAMxfhwfk',
    appId: '1:245625075246:ios:75abe911eb2a6b513011bf',
    messagingSenderId: '245625075246',
    projectId: 'acm-hackathon-a7eeb',
    storageBucket: 'acm-hackathon-a7eeb.firebasestorage.app',
    iosBundleId: 'com.example.acmhackthon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuZzzlszW9EAIZlbIm_RD2DW16dfBvb0g',
    appId: '1:245625075246:web:550517d54ce996a33011bf',
    messagingSenderId: '245625075246',
    projectId: 'acm-hackathon-a7eeb',
    authDomain: 'acm-hackathon-a7eeb.firebaseapp.com',
    storageBucket: 'acm-hackathon-a7eeb.firebasestorage.app',
    measurementId: 'G-918DF0ELPR',
  );
}
